apiVersion: v1
kind: Service
metadata:
  name: app-hgomez202103718-service
spec:
  selector:
    app: app-hgomez202103718
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31110
