version: '3.8'

services:
  mysqldb_hgomez202103718:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=hgomez202103718
    ports:
      - 3307:3306 #PUERTO_LOCAL:PUERTO_CONTENEDOR

  app_hgomez202103718:
    build: .
    command: npm start
    depends_on:
      - mysqldb_hgomez202103718
    ports:
      - 3000:3000
